# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8baea19604822ae5da551be1bbd03acec2788ec81af720babd41cfeca1e20f6df89be2d9a9309898c425d98fb5c027da7f1866c01e7a5a5b5d9f2147864ae850

test:
  secret_key_base: f99cf20a833b40cc6517f61f5663ff87e0a77ecad86d4ff3bd22f4a8573559f675f7a52941c7adfe06d3db5a6acc21d21f7542c731bd43d82b3684ca2be45756

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
